# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
fi


#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

case $OSTYPE in
  darwin*)
    if [ -x "${HOME}/bin/macos/Emacs.sh" ] ; then
      use_editor="${HOME}/bin/macos/Emacs.sh"
    else
      use_editor="emacsclient -c"
    fi
    export EDITOR="${use_editor}"
    ;;
  *)
    # create new frame in windowing env
    if (( $+commands[vim] )) ; then
      export EDITOR="${EMACSCLIENT} -a vim --create-frame"
    else
      export EDITOR="${EMACSCLIENT} -a vi --create-frame"
    fi
    ;;
esac


export VISUAL=$EDITOR
export PAGER='less'


#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)




#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# # added by rustup - enable prezto module instead
# export PATH="$HOME/.cargo/bin:$PATH"
