# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# for powerlevel10k config -
# https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration
[[ $TERM == xterm* ]] || : ${PURE_POWER_MODE:=portable}
source ~/.purepower
# handy workaround if terminal can't handle: PURE_POWER_MODE=portable exec zsh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs.


# # Use emacs keybindings even if our EDITOR is set to vi
# bindkey -e

# https://github.com/mika/zsh-pony#remove-last-part-from-directory-name
# Remove last part from directory name
slash-backward-kill-word() {
    local WORDCHARS="${WORDCHARS:s@/@}"
    zle backward-kill-word
}
zle -N slash-backward-kill-word

# bind to <esc>-<backspace>
bindkey '\e^?' slash-backward-kill-word


# https://github.com/mika/zsh-pony#insert-a-timestamp-on-the-command-line-yyyy-mm-dd
# Insert a Date timestamp on the command line (yyyy-mm-dd)
insert-datestamp() { LBUFFER+=${(%):-'%D{%Y-%m-%d}'}; }
zle -N insert-datestamp
bindkey '^Ed' insert-datestamp


# completions on macOS:
# MAIN: /usr/local/share/zsh/site-functions
# other: /usr/local/opt/curl/share/zsh/site-functions

# # https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
# if type brew &>/dev/null; then
#   FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
# fi

# custom completions in ~/.zsh/completions
if [[ -d ${ZDOTDIR:-$HOME}/.zsh/completions ]] ; then
    fpath=(${ZDOTDIR:-$HOME}/.zsh/completions $fpath)
    compinit -i -C
fi

# https://hub.github.com/
# brew install hub || sudo snap install hub --classic
if [[ -x /usr/local/bin/hub || -x /snap/bin/hub ]]
then
    # eval "$(hub alias -s)"
	alias git=hub
fi
